AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  GetListFunction:
    Type: AWS::Serverless::Function
    Properties:
      Role: arn:aws:iam::092514897611:role/sam-flutter-demo-role-padrao
      Handler: index.handler
      Runtime: nodejs10.x
      Events:
        HelloWorldApi:
          Type: Api
          Properties:
            Path: /places
            Method: GET
  # CreateItemFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     Handler: createItem/index.handler
  #     Runtime: nodejs8.10
  #     Events:
  #       Stream:
  #         Type: DynamoDB
  #         Properties:
  #           Stream: !GetAtt DynamoDBTable.StreamArn
  #           BatchSize: 100
  #           StartingPosition: TRIM_HORIZON
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: munchies
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE